CREATE TABLE KhoaHoc (
    MaKH VARCHAR(20) PRIMARY KEY,
    TenKH VARCHAR(100),
    ChiTiet TEXT
);

CREATE TABLE NhanVien (
    MaNV VARCHAR(20) PRIMARY KEY,
    TenNV VARCHAR(100),
    SDT VARCHAR(20),
    Email VARCHAR(100),
    ChucVu VARCHAR(50)
);

CREATE TABLE LopHoc (
    MaLH VARCHAR(20) PRIMARY KEY,
    MaNV VARCHAR(20) REFERENCES NhanVien(MaNV),
    MaKH VARCHAR(20) REFERENCES KhoaHoc(MaKH),
    TenLopHoc VARCHAR(100),
    NgayBatDau DATE,
    NgayKetThuc DATE
);

CREATE TABLE HocVien (
    MaHV VARCHAR(20) PRIMARY KEY,
    HoTen VARCHAR(100),
    NgaySinh DATE,
    CCCD VARCHAR(20),
    DiaChi TEXT,
    SDT VARCHAR(20),
    Email VARCHAR(100),
    TenDangNhap VARCHAR(50),
    MatKhau VARCHAR(100)
);

CREATE TABLE HoaDon (
    MaHD VARCHAR(20) PRIMARY KEY,
    MaHV VARCHAR(20) REFERENCES HocVien(MaHV),
    MaLH VARCHAR(20) REFERENCES LopHoc(MaLH),
    TenLopHoc VARCHAR(100),
    GiaTien INTEGER,
    TinhTrang VARCHAR(20)
);

CREATE TABLE DiemDanh (
    MaLH VARCHAR(20) REFERENCES LopHoc(MaLH),
    MaHV VARCHAR(20) REFERENCES HocVien(MaHV),
    NgayHoc DATE,
    ThamGia BOOLEAN,
    PRIMARY KEY (MaLH, MaHV, NgayHoc)
);

CREATE TABLE DiemSo (
    MaHV VARCHAR(20) REFERENCES HocVien(MaHV),
    MaLH VARCHAR(20) REFERENCES LopHoc(MaLH),
    MaNV VARCHAR(20) REFERENCES NhanVien(MaNV),
    Diem INTEGER,
    PRIMARY KEY (MaHV, MaLH)
);