# Generated by Django 5.2 on 2025-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("giao_vu", "Giáo vụ"),
                    ("giang_vien", "Giảng viên"),
                    ("hoc_vien", "Học viên"),
                    ("giam_doc", "Giám đốc"),
                ],
                max_length=20,
            ),
        ),
    ]
